version: "3"
services:
  mongo:
    image: "mongo"
    container_name: mongodb
    hostname: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 27017:27017

    volumes:
      - ./data/db:/data/db

  app:
    image: song22an/virspit-listing:latest
    container_name: virspit-listing
    ports:
      - 8081:8080
    build: .
    depends_on:
      - mongo
    volumes:
      - ./config/listing.yml:/app/application.yml